  0%|          | 0/2500 [00:00<?, ?it/s]  0%|          | 0/2500 [00:10<?, ?it/s]
Traceback (most recent call last):
  File "/Users/shouchenchen/Desktop/CS/IntroToCV/assignments/02_assignment/cifar-10/train.py", line 164, in <module>
    run(args)
  File "/Users/shouchenchen/Desktop/CS/IntroToCV/assignments/02_assignment/cifar-10/train.py", line 139, in run
    train(epoch, model, optimizer, criterion, train_loader, writer)
  File "/Users/shouchenchen/Desktop/CS/IntroToCV/assignments/02_assignment/cifar-10/train.py", line 63, in train
    for imgs, labels in tqdm.tqdm(train_loader):
  File "/Users/shouchenchen/mambaforge/lib/python3.10/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/Users/shouchenchen/mambaforge/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/Users/shouchenchen/mambaforge/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/Users/shouchenchen/mambaforge/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/Users/shouchenchen/mambaforge/lib/python3.10/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/Users/shouchenchen/mambaforge/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/Users/shouchenchen/mambaforge/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/Users/shouchenchen/mambaforge/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/Users/shouchenchen/Desktop/CS/IntroToCV/assignments/02_assignment/cifar-10/dataset.py", line 82, in __getitem__
    img=trans_list[id](img)
TypeError: list indices must be integers or slices, not builtin_function_or_method

